Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision "shell", inline: <<-SHELL
    echo deb http://deb.debian.org/debian/ stretch contrib | sudo tee -a /etc/apt/sources.list
    apt-get update
    apt-get install -y ooniprobe
    touch /var/lib/ooni/initialized
    ooniprobe -P https --bouncer=https://ams-pg.ooni.org -o /vagrant/legacy_https.jsonl \
        web_connectivity -u http://mail.google.com
    ooniprobe -P onion --bouncer=httpo://guegdifjy7bjpequ.onion -o /vagrant/legacy_onion.jsonl \
        web_connectivity -u http://mail.google.com
  SHELL
end
