#!/bin/bash
set -ex
brew install ooniprobe
install -d $HOME/.ooni
touch $HOME/.ooni/initialized
cp config/ooniprobe.conf $HOME/.ooni/
ooniprobe -P https --bouncer=https://ams-pg.ooni.org  \
    web_connectivity -u http://mail.google.com
