#!/bin/bash
set -ex
brew tap measurement-kit/measurement-kit
brew install measurement-kit
for f in asn.mmdb.gz ca-bundle.pem.gz country.mmdb.gz; do
  curl -fsSLO https://github.com/ooni/probe-assets/releases/download/20200821081345/$f
  gunzip -f $f
done
test $# -eq 1 || exit 1
measurement_kit --bouncer $1                             \
                -o output/mk.jsonl                       \
                --ca-bundle-path ca-bundle.pem           \
                --geoip-country-path country.mmdb        \
                --geoip-asn-path asn.mmdb                \
                web_connectivity                         \
                -u http://mail.google.com
