#!/bin/bash
set -ex
brew tap measurement-kit/measurement-kit
brew install measurement-kit
for f in asn.mmdb.gz ca-bundle.pem.gz country.mmdb.gz; do
  curl -fsSLO https://github.com/ooni/probe-assets/releases/download/20200821081345/$f
  gunzip -f $f
done
measurement_kit --bouncer $(cat ./config/backend/https)  \
                --ca-bundle-path ca-bundle.pem           \
                --geoip-country-path country.mmdb        \
                --geoip-asn-path asn.mmdb                \
                web_connectivity                         \
                -u http://mail.google.com
