#!/bin/bash
set -ex
go get -v github.com/ooni/probe-engine/cmd/miniooni
miniooni="$(go env GOPATH)/bin/miniooni --probe-services https://ams-pg.ooni.org/"
$miniooni -i http://mail.google.com web_connectivity
