#!/bin/bash
set -ex
brew install ooniprobe
install -d $HOME/.ooni
touch $HOME/.ooni/initialized
cp config/ooniprobe.conf $HOME/.ooni/
ooniprobe --bouncer=httpo://guegdifjy7bjpequ.onion  \
    web_connectivity -u http://mail.google.com
