#!/bin/bash
set -ex

# Surprisingly Debian9 uses /var/lib/ooni as opposed to $HOME/.ooni so
# we receive this information as the first argument
test $# -eq 3 || exit 1
install -d $1
touch $1/initialized

ooniprobe -P https --bouncer=$2 -o output/legacy_https.jsonl \
    web_connectivity -u http://mail.google.com

ooniprobe -P onion --bouncer=$3 -o output/legacy_onion.jsonl \
    web_connectivity -u http://mail.google.com
 