#!/bin/bash
set -ex
apt-get update
apt-get install -y build-essential libdumbnet-dev libpcap-dev tor \
        libgeoip-dev libffi-dev python-dev python-pip libssl-dev curl
pip install -r ./config/ooniprobe220pip/requirements.txt
curl -fsSLO https://github.com/ooni/probe-legacy/archive/v2.2.0.tar.gz
tar -xzf v2.2.0.tar.gz
cd probe-legacy-2.2.0
python setup.py install
cd ..
./script/ooniprobe "$@"
