name: debian9
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        version:
        - "ooniprobe_2.0.2"
        - "ooniprobe_2.1.0"
        - "ooniprobe_2.2.0"
        - "ooniprobe_2.3.0"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: vagrant plugin install vagrant-scp
      - run: vagrant up ${{ matrix.version }}
        working-directory: ./vagrant/debian9
      - run: vagrant scp ${{ matrix.version }}:/vagrant/*.jsonl ../../output/
        working-directory: ./vagrant/debian9
      - run: go run ./script/postprocess.go
