name: fetchback
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: brew install jq
      - run: ./script/fetchbacktest
