name: legacydebian8
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner:
        - legacydebian8
    steps:
      - if: "${{ matrix.runner == 'miniooni' }}"
        uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: "./script/${{ matrix.runner }}"
