# As of 2020-09-24 we have a significant user base running ooniprobe-cli
# from Linux systems. The version they're running contains MK 0.10.11. So
# here we're using the docker container that built such version.
#
# See also analysis at https://github.com/ooni/backend/issues/446#issuecomment-697172389.
#
# We still see 1.399000% of measurements as of 2020-11-13 coming from
# cli v3.0.0. which includes MK v0.10.11.
name: libmk0.10.11
on:
  pull_request:
  push:
  schedule:
    - cron: "5 */2 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extraoptions:
        - ""
        - "--bouncer=https://ams-pg-test.ooni.org"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: |
          for f in asn.mmdb.gz ca-bundle.pem.gz country.mmdb.gz; do
            curl -fsSLO https://github.com/ooni/probe-assets/releases/download/20200821081345/$f
            gunzip -f $f
          done
          docker run -v`pwd`:/mk -w/mk openobservatory/mk-alpine:20200226 \
            measurement_kit -o output/mk.jsonl                            \
                {{ matrix.extraoptions }}                                 \
                --ca-bundle-path ca-bundle.pem                            \
                --geoip-country-path country.mmdb                         \
                --geoip-asn-path asn.mmdb                                 \
                web_connectivity                                          \
                -u http://mail.google.com
      - run: go run ./script/postprocess.go
