# As of 2020-09-24 we have a significant fraction of our users running
# ooniprobe 2.3.0 from macOS. So, here we just do that.
#
# See also https://github.com/ooni/backend/issues/446#issuecomment-697172389
name: macos10.15
on:
  pull_request:
  push:
  schedule:
    - cron: "10 */2 * * *"
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      # Limitation: we test the cloudfronted endpoint as a normal HTTPS endpoint.
      - run: |
          brew install ooniprobe
          install -d $HOME/.ooni
          touch $HOME/.ooni/initialized
          ooniprobe -P https --bouncer=https://ams-pg.ooni.org -o ./output/https.jsonl \
            web_connectivity -u http://mail.google.com
          ooniprobe -P https --bouncer=https://dvp6h0xblpcqp.cloudfront.net -o ./output/https.jsonl \
            web_connectivity -u http://mail.google.com
          ooniprobe -P onion --bouncer=httpo://guegdifjy7bjpequ.onion -o ./output/onion.jsonl \
            web_connectivity -u http://mail.google.com
      - run: go run ./script/postprocess.go
