name: measurementkit
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: |
          bouncer=https://ams-pg.ooni.org
          brew tap measurement-kit/measurement-kit
          brew install measurement-kit
          for f in asn.mmdb.gz ca-bundle.pem.gz country.mmdb.gz; do
            curl -fsSLO https://github.com/ooni/probe-assets/releases/download/20200821081345/$f
            gunzip -f $f
          done
          measurement_kit --bouncer $bouncer             \
                -o output/mk.jsonl                       \
                --ca-bundle-path ca-bundle.pem           \
                --geoip-country-path country.mmdb        \
                --geoip-asn-path asn.mmdb                \
                web_connectivity                         \
                -u http://mail.google.com
      - run: go run ./script/postprocess.go
