name: measurementkit
on:
  pull_request:
  push:
  schedule:
    - cron: "34 * * * *"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./script/measurementkit
