# Not very popular among users but yet useful to garner confidence that
# MK is WAI, modulo possible dependencies issues.
#
# As of 2020-11-13, we don't have any significant OONI client running MK
# but we know that there are many legacy clients running `ndt` using version
# of MK compiled by people independently of OONI. So we are keeping this
# workflow for now, to be sure we are not breaking this use case.
#
# Because this is increasingly less important to us, we only run tests
# using OONI's testing infrastructure.
name: measurementkit
on:
  pull_request:
  push:
  schedule:
    - cron: "15 */8 * * *"
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: |
          brew tap measurement-kit/measurement-kit
          brew install measurement-kit
          for f in asn.mmdb.gz ca-bundle.pem.gz country.mmdb.gz; do
            curl -fsSLO https://github.com/ooni/probe-assets/releases/download/20200821081345/$f
            gunzip -f $f
          done
          measurement_kit -o output/mk.jsonl             \
                --bouncer=https://ams-pg-test.ooni.org/  \
                --ca-bundle-path ca-bundle.pem           \
                --geoip-country-path country.mmdb        \
                --geoip-asn-path asn.mmdb                \
                web_connectivity                         \
                -u http://mail.google.com
      - run: go run ./script/postprocess.go -expected 1
