name: measurementkit
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        runner:
        - measurementkit
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: "./script/${{ matrix.runner }}"
      - run: go run ./script/postprocess.go
