name: miniooni
on:
  pull_request:
  push:
  schedule:
    - cron: "17 * * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: ./script/miniooni
