name: miniooni
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        runner:
        - miniooni
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: "./script/${{ matrix.runner }}"
      - run: go run ./script/postprocess.go
