name: ooniprobe210debian9
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        options:
        - "/var/lib/ooni https://ams-pg.ooni.org httpo://guegdifjy7bjpequ.onion"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: docker build -t x ./docker/ooniprobe210debian9
      - run: docker run -v`pwd`:/ooni -w/ooni x ./script/ooniprobe ${{ matrix.options }}
      - run: go run ./script/postprocess.go
