name: ooniprobe210
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        options:
        - "/var/lib/ooni https://ams-pg.ooni.org httpo://guegdifjy7bjpequ.onion"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: docker build -t ooniprobe210 ./docker/ooniprobe210
      - run: docker run -v`pwd`:/ooni -w/ooni ooniprobe210 ./script/legacycore ${{ matrix.options }}
      - run: go run ./script/postprocess.go
