name: ooniprobe220pip
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner:
        - debian:8
        - ubuntu:16.04
        command:
        - "./script/ooniprobe220pip /var/lib/ooni https://ams-pg.ooni.org httpo://guegdifjy7bjpequ.onion"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: docker run -v`pwd`:/ooni -w/ooni ${{ matrix.runner }} ${{ matrix.command }}
      - run: go run ./script/postprocess.go
