name: ooniprobe3debian
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "20 */8 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extraoptions:
        - ""
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-key adv --verbose --keyserver keyserver.ubuntu.com --recv-keys '8756C4F765C9AC3CB6B85D62379CE192D401AB61'
      - run: echo "deb https://dl.bintray.com/ooni/ooniprobe-debian/ unstable main" | sudo tee /etc/apt/sources.list.d/ooniprobe.list
      - run: sudo apt update
      - run: sudo apt install ooniprobe-cli
      - run: ooniprobe onboard --yes
      - run: ooniprobe ${{ matrix.extraoptions }} run im
