# TODO(bassosimone): we should move this workflow in ooni/probe-cli.
name: ooniprobe3debian
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "20 */8 * * *"
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        extraoptions:
        - ""
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-key adv --verbose --keyserver hkp://keyserver.ubuntu.com --recv-keys 'B5A08F01796E7F521861B449372D1FF271F2DD50'
      - run: echo "deb http://deb.ooni.org/ unstable main" | sudo tee /etc/apt/sources.list.d/ooniprobe.list
      - run: sudo apt update
      - run: sudo apt install ooniprobe-cli
      - run: ooniprobe onboard --yes
      - run: ooniprobe ${{ matrix.extraoptions }} run im
