name: "probeengine"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        version:
        - "master"
        - "v0.15.1"
        - "7ac6a37960"
        - "4bcf3efabf"
        - "v0.13.2"
        - "v0.11.0"
        run-cmd:
        - "./miniooni --probe-services=https://ams-pg.ooni.org -o output/miniooni.jsonl"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: git clone https://github.com/ooni/probe-engine
      - run: cd probe-engine && git checkout "${{ matrix.version }}"
      - run: cd probe-engine && go build -tags nomk -o ../miniooni -v ./cmd/miniooni
      - run: "${{ matrix.run-cmd }}" -i http://mail.google.com web_connectivity
      - run: "${{ matrix.run-cmd }}" sni_blocking
      - run: "${{ matrix.run-cmd }}" tor
      - run: "${{ matrix.run-cmd }}" psiphon
      - run: go run ./script/postprocess.go
