name: "probeengine1"
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "25 */8 * * *"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        version:
        - "v3.5.2"  # cli v3.5.2 [2021-03-04; 15.99%]
        - "v3.5.1"  # android v2.9.3 [2021-03-04; 5.95%]
        options:
        - "-o output/miniooni.jsonl"
        - "--probe-services=https://dvp6h0xblpcqp.cloudfront.net -o output/miniooni.jsonl"
        - "--probe-services=https://ams-pg-test.ooni.org -o output/miniooni.jsonl"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: git clone https://github.com/ooni/probe-cli
      - run: cd probe-cli && git checkout "${{ matrix.version }}"
      - run: cd probe-cli && go build -o ../miniooni -v ./internal/cmd/miniooni
      - run: ./miniooni ${{ matrix.options }} -i http://mail.google.com web_connectivity
      - run: ./miniooni ${{ matrix.options }} tor
      - run: ./miniooni ${{ matrix.options }} psiphon
      - run: go run ./script/postprocess.go -expected 3
