name: "probecli"
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "25 */8 * * *"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        version:
        - "v3.9.2"  # cli v3.9.2 and desktop-unattended 3.9.2 [2021-04-07; 1.49% and 29.4%]
        - "v3.9.1"  # cli v3.9.1 [2021-04-07; 1.48%]
        - "v3.9.0"  # cli v3.9.0 and v2.11.0 [2021-04-07; 1.3% and 2.91%]
        - "v3.8.0"  # desktop-unattended v3.8.0 and cli v3.8.0 [2021-04-07; 1.28% and 3.25%]
        - "v3.6.0"  # cli v3.6.0 [2021-05-13; ~1.2%]
        - "v3.5.2"  # cli v3.5.2 [2021-05-13; ~1.0%]
        options:
        - "-o output/miniooni.jsonl"
        - "--probe-services=https://dvp6h0xblpcqp.cloudfront.net -o output/miniooni.jsonl"
        - "--probe-services=https://ams-pg-test.ooni.org -o output/miniooni.jsonl"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: git clone https://github.com/ooni/probe-cli
      - run: cd probe-cli && git checkout "${{ matrix.version }}"
      - run: cd probe-cli && if test -d ./internal/cmd/getresources; then go run ./internal/cmd/getresources; fi
      - run: cd probe-cli && go build -o ../miniooni -v ./internal/cmd/miniooni
      - run: ./miniooni --yes ${{ matrix.options }} -i http://mail.google.com web_connectivity
      - run: ./miniooni --yes ${{ matrix.options }} tor
      - run: ./miniooni --yes ${{ matrix.options }} psiphon
      - run: go run ./script/postprocess.go -expected 3
