# Ensures that recent versions of ooni/probe-engine work with the new
# OONI API we're sketching out. As of 2020-09-24, we've not released any
# stable version of the probe-engine yet. In any case, we always want
# to keep master here to ensure we're not breaking things
name: "probeengine"
on:
  pull_request:
  push:
  schedule:
    - cron: "25 */8 * * *"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        version:
        - "master"
        - "v0.18.0"  # {ios,android} v2.7.0; desktop v3.0.4; cli v3.0.9 [2020-11-13]
        options:
        - "-o output/miniooni.jsonl"
        - "--probe-services=https://dvp6h0xblpcqp.cloudfront.net -o output/miniooni.jsonl"
        - "--probe-services=https://ams-pg-test.ooni.org -o output/miniooni.jsonl"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: git clone https://github.com/ooni/probe-engine
      - run: cd probe-engine && git checkout "${{ matrix.version }}"
      - run: cd probe-engine && go build -o ../miniooni -v ./cmd/miniooni
      - run: ./miniooni ${{ matrix.options }} -i http://mail.google.com web_connectivity
      - run: ./miniooni ${{ matrix.options }} tor
      - run: ./miniooni ${{ matrix.options }} psiphon
      - run: go run ./script/postprocess.go -expected 3
