name: "probecli"
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "25 */8 * * *"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        version:
        - "v3.9.0"  # cli v3.9.0 [2021-04-07; 1.3%]
        - "v3.8.0"  # cli v3.8.0 and v2.10.1 [2021-04-07; 8% and 5.2%]
        - "v3.5.2"  # cli v3.5.2 [2021-04-07; 2.8%]
        options:
        - "-o output/miniooni.jsonl"
        - "--probe-services=https://dvp6h0xblpcqp.cloudfront.net -o output/miniooni.jsonl"
        - "--probe-services=https://ams-pg-test.ooni.org -o output/miniooni.jsonl"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - run: git clone https://github.com/ooni/probe-cli
      - run: cd probe-cli && git checkout "${{ matrix.version }}"
      - run: cd probe-cli && go build -o ../miniooni -v ./internal/cmd/miniooni
      - run: ./miniooni --yes ${{ matrix.options }} -i http://mail.google.com web_connectivity
      - run: ./miniooni --yes ${{ matrix.options }} tor
      - run: ./miniooni --yes ${{ matrix.options }} psiphon
      - run: go run ./script/postprocess.go -expected 3
