name: "probeengine"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        version:
        - "master"
        - "v0.15.1"
        - "7ac6a37960"
        - "4bcf3efabf"
        - "v0.13.2"
        - "v0.11.0"
        runner:
        - miniooni
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: git clone --branch "${{ matrix.version }}" --depth 1 https://github.com/ooni/probe-engine
      - run: cd probe-engine && go build -tags nomk -o ../miniooni -v ./cmd/miniooni
